exception TODO(string);

let todo = (message: string) => raise(TODO(message));
